default: &default
  adapter: oracle_enhanced
  database: //127.0.0.1/orcl:1521

development:
  <<: *default
  username: dolf_development
  password: password

test: &test
  <<: *default
  username: dolf_test
  password: password

production:
  <<: *default
  username: dolf_production
  password: password

cucumber:
  <<: *test